# Generated by Django 3.1.1 on 2020-12-11 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20201211_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultsettingsmodel',
            name='default_client_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.orderclienttypemodel', verbose_name='Стандартный тип клиента'),
        ),
        migrations.AlterField(
            model_name='defaultsettingsmodel',
            name='default_order_status_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.orderstatusmodel', verbose_name='Стандартный статус заказа'),
        ),
        migrations.AlterField(
            model_name='orderclienttypemodel',
            name='client_type',
            field=models.CharField(max_length=255, unique=True, verbose_name='Тип клиента'),
        ),
        migrations.AlterField(
            model_name='orderstatusmodel',
            name='status',
            field=models.CharField(max_length=255, unique=True, verbose_name='Статус заказа'),
        ),
    ]
