# Generated by Django 3.1.1 on 2020-12-11 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_delete_defaultsettingsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.orderclienttypemodel', verbose_name='Стандартный тип клиента')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.orderstatusmodel', verbose_name='Стандартный статус заказа')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
