# Generated by Django 3.1.1 on 2020-12-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_defaultsettingsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultsettingsmodel',
            options={'verbose_name': 'Настройка по умолчанию', 'verbose_name_plural': 'Настройки по умолчанию'},
        ),
    ]
