# Generated by Django 3.1.1 on 2020-12-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_defaultsettingsmodel_starmap_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultsettingsmodel',
            name='starmap_time',
            field=models.TimeField(help_text='Вводить в формате 18:20', verbose_name='Время звездного неба'),
        ),
    ]
