# Generated by Django 3.1.1 on 2020-12-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_auto_20201212_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatusmodel',
            old_name='status',
            new_name='order_status',
        ),
    ]
