# Generated by Django 3.1.1 on 2020-12-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_auto_20201212_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultsettingsmodel',
            name='starmap_angle',
            field=models.PositiveSmallIntegerField(default=1, help_text='В градусах', verbose_name='Угол поворота звездной карты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultsettingsmodel',
            name='starmap_height',
            field=models.PositiveSmallIntegerField(default=1, help_text='В пикселях', verbose_name='Высота звездной карты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultsettingsmodel',
            name='starmap_width',
            field=models.PositiveSmallIntegerField(default=1, help_text='В пикселях', verbose_name='Ширина звездной карты'),
            preserve_default=False,
        ),
    ]
