# Generated by Django 3.1.1 on 2020-10-07 01:55

from django.db import migrations, models
import django.db.models.deletion
import src.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StarmapCatalogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название звездной карты')),
                ('image', models.ImageField(upload_to=src.utils.get_starmap_image_upload_path_in_catalog, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Каталог звездных карт',
                'verbose_name_plural': 'Каталог звездных карт',
            },
        ),
        migrations.CreateModel(
            name='StarmapOrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=255, verbose_name='Адресс')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('date', models.DateField(verbose_name='Дата')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('text', models.CharField(max_length=50, verbose_name='Текст')),
                ('additional_information', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('is_logo', models.BooleanField(default=True, verbose_name='Логотип')),
                ('is_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания заказа')),
                ('is_changed', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения заказа')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.starmapcatalogmodel', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Заказ звездной карты',
                'verbose_name_plural': 'Заказы звездных карт',
            },
        ),
    ]
