# Generated by Django 3.1.1 on 2020-12-11 04:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarmapSizeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255, verbose_name='Размер звездной карты')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='StarmapTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название звездной карты')),
                ('image', models.ImageField(upload_to=src.utils.get_starmap_image_upload_path_in_catalog, verbose_name='Изображение')),
                ('shade_galaxy', models.BooleanField(default=True, verbose_name='Сияние')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='StarmapOrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=255, verbose_name='Адресс')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('date', models.DateField(verbose_name='Дата')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('text', models.CharField(max_length=50, verbose_name='Текст')),
                ('latitude', models.FloatField(blank=True, help_text='От -90 до 90 включительно', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, help_text='От -180 до 180 включительно', null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота')),
                ('additional_information', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('is_logo', models.BooleanField(default=True, verbose_name='Логотип')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания заказа')),
                ('changed_datetime', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения заказа')),
                ('client_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.orderclienttypemodel', verbose_name='Тип клиента')),
                ('starmap_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.starmapsizemodel', verbose_name='Размер звездной карты')),
                ('starmap_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.starmaptypemodel', verbose_name='Тип звездной карты')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.orderstatusmodel', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
