# Generated by Django 3.1.1 on 2020-12-11 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20201211_0736'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starmapordermodel',
            name='client_type',
            field=models.ForeignKey(default='Клиент', on_delete=django.db.models.deletion.PROTECT, to='settings.orderclienttypemodel', verbose_name='Тип клиента'),
        ),
        migrations.AlterField(
            model_name='starmapordermodel',
            name='status',
            field=models.ForeignKey(default='Новый заказ', null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.orderstatusmodel', verbose_name='Статус'),
        ),
    ]
