# Generated by Django 3.1.1 on 2020-10-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='starmapcatalogmodel',
            options={'verbose_name': 'Каталог звездных карт', 'verbose_name_plural': 'Каталог звездных карт'},
        ),
        migrations.AlterModelOptions(
            name='starmapordermodel',
            options={'verbose_name': 'Заказ звездной карты', 'verbose_name_plural': 'Заказы звездных карт'},
        ),
        migrations.AlterField(
            model_name='starmapcatalogmodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название звездной карты'),
        ),
    ]
