# Generated by Django 3.1.1 on 2020-10-07 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starmapordermodel',
            old_name='is_changed',
            new_name='changed_datetime',
        ),
        migrations.RenameField(
            model_name='starmapordermodel',
            old_name='is_created',
            new_name='created_datetime',
        ),
    ]
