# Generated by Django 3.1.1 on 2020-10-07 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201007_0329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StarmapCatalogModel',
            new_name='StarmapModel',
        ),
        migrations.RemoveField(
            model_name='starmapordermodel',
            name='template',
        ),
        migrations.AddField(
            model_name='starmapordermodel',
            name='starmap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='order.starmapmodel', verbose_name='Звездная карта'),
            preserve_default=False,
        ),
    ]
