# Generated by Django 3.1.1 on 2020-12-11 13:00

from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_delete_defaultsettingsmodel'),
        ('order', '0002_auto_20201211_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starmapordermodel',
            name='client_type',
            field=models.ForeignKey(default=order.models.get_default_client_type, on_delete=django.db.models.deletion.PROTECT, to='settings.orderclienttypemodel', verbose_name='Тип клиента'),
        ),
        migrations.AlterField(
            model_name='starmapordermodel',
            name='status',
            field=models.ForeignKey(default=order.models.get_default_order_status, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.orderstatusmodel', verbose_name='Статус'),
        ),
    ]
