# Generated by Django 3.1.1 on 2020-10-07 04:13

from django.db import migrations, models
import django.db.models.deletion
import src.utils


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201007_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starmapordermodel',
            name='starmap',
        ),
        migrations.AddField(
            model_name='starmapordermodel',
            name='starmap_image',
            field=models.FileField(default=1, upload_to=src.utils.get_starmap_image_upload_path_by_id, verbose_name='Звездная карта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='starmapordermodel',
            name='starmap_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='order.starmapmodel', verbose_name='Шаблон звездной карты'),
            preserve_default=False,
        ),
    ]
