# Generated by Django 3.1.1 on 2020-12-12 17:15

from django.db import migrations, models
import django.db.models.deletion
import settings.services


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_auto_20201212_2011'),
        ('order', '0003_auto_20201211_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='starmapordermodel',
            name='starmap_time',
            field=models.TimeField(default=settings.services.get_default_starmap_time, verbose_name='Время звездного неба'),
        ),
        migrations.AlterField(
            model_name='starmapordermodel',
            name='status',
            field=models.ForeignKey(default=settings.services.get_default_order_status, on_delete=django.db.models.deletion.PROTECT, to='settings.orderstatusmodel', verbose_name='Статус'),
        ),
    ]
