# Generated by Django 3.1.1 on 2020-12-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20201212_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starmapordermodel',
            old_name='status',
            new_name='order_status',
        ),
    ]
