# Generated by Django 3.1.1 on 2020-10-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20201007_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='starmapmodel',
            name='shade_galaxy',
            field=models.BooleanField(default=True, verbose_name='Сияние'),
        ),
    ]
