# Generated by Django 3.1.1 on 2020-10-07 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20201007_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starmapordermodel',
            name='starmap_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.starmapmodel', verbose_name='Тип звездной карты'),
        ),
    ]
