# Generated by Django 3.1.1 on 2020-10-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_starmapmodel_shade_galaxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarmapSizeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255, verbose_name='Размер звездной карты')),
            ],
            options={
                'verbose_name': 'Размер звездной карты',
                'verbose_name_plural': 'Размер звездных карт',
            },
        ),
    ]
