# Generated by Django 3.1.1 on 2020-10-09 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_starmapsizemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='starmapordermodel',
            name='starmap_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='order.starmapsizemodel', verbose_name='Размер звездной карты'),
            preserve_default=False,
        ),
    ]
