# Generated by Django 3.1.1 on 2020-10-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_starmapordermodel_starmap_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='starmapmodel',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AlterModelOptions(
            name='starmapordermodel',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='starmapsizemodel',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AddField(
            model_name='starmapordermodel',
            name='latitude',
            field=models.FloatField(blank=True, default=1, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='starmapordermodel',
            name='longitude',
            field=models.FloatField(blank=True, default=1, verbose_name='Долгота'),
            preserve_default=False,
        ),
    ]
