# Generated by Django 3.1.1 on 2020-10-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20201010_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starmapordermodel',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='starmapordermodel',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
