# Generated by Django 3.1.1 on 2020-10-10 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20201010_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starmapordermodel',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Если вводите широту, то и долготу тоже. Пример: 55.75697', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='starmapordermodel',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Если вводите долготу, то и ширину тоже. Пример: 37.61502', null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота'),
        ),
    ]
