# Generated by Django 3.1.1 on 2020-11-26 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20201010_0736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StarmapModel',
            new_name='StarmapTypeModel',
        ),
    ]
